// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKmF9hUafCnNnnDgz8G8KCTKRHeWGobY',
    appId: '1:460419570568:web:7b34d3cf1d044f5762f83d',
    messagingSenderId: '460419570568',
    projectId: 'muhtadi-57420',
    authDomain: 'muhtadi-57420.firebaseapp.com',
    storageBucket: 'muhtadi-57420.appspot.com',
    measurementId: 'G-X4W62DSVXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTotS8UJ-h3wzUY--T9EgCk8brG8EcIAQ',
    appId: '1:460419570568:android:94e510f50cbbff0462f83d',
    messagingSenderId: '460419570568',
    projectId: 'muhtadi-57420',
    storageBucket: 'muhtadi-57420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0mtapXZvv_2HOLjlYvYKcXb1P5bDbsJk',
    appId: '1:460419570568:ios:f934a88ef137293262f83d',
    messagingSenderId: '460419570568',
    projectId: 'muhtadi-57420',
    storageBucket: 'muhtadi-57420.appspot.com',
    iosBundleId: 'com.example.muhtadi',
  );
}
